return {
  "nvim-treesitter/nvim-treesitter",
  -- branch = "master",
  build = ":TSUpdate",
  lazy = false,
  config = function ()
    local configs = require("nvim-treesitter.configs")

    configs.setup({
      ensure_installed = {
        "bash",
        "c",
        "c_sharp",
        "cpp",
        "css",
        "csv",
        "gdscript",
        "git_config",
        "git_rebase",
        "gitattributes",
        "gitcommit",
        "gitignore",
        "go",
        "gomod",
        "gosum",
        "gotmpl",
        "html",
        "htmldjango",
        "javascript",
        "json",
        "jsonc",
        "lua",
        "luadoc",
        "markdown",
        "nginx",
        "powershell",
        "python",
        "query",
        "ruby",
        "rust",
        "sql",
        "svelte",
        "toml",
        "tsv",
        "tsx",
        "typescript",
        "vim",
        "vimdoc",
        "xml",
        "zig",
      },
      sync_install = false,
      highlight = { enable = true },
      indent = { enable = true },
    })
  end,
  opts = {},
}
